# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHSMCnN9WE_F9UDy7JzmwMU84ZsFYuYH
"""

!pip install tensorflow keras_cv --upgrade --quiet

import time
import keras_cv
from tensorflow import keras
import matplotlib.pyplot as plt

model = keras_cv.models.StableDiffusion(img_width=512, img_height=512)

input_line = input("Describe what you would like to draw (and then hit the 'enter' button):")

images = model.text_to_image(input_line, batch_size=3)

def plot_images(images):
    plt.figure(figsize=(20, 20))
    for i in range(len(images)):
        ax = plt.subplot(1, len(images), i + 1)
        plt.imshow(images[i])
        plt.axis("off")

plot_images(images)

